version: "3"
services:

  vprodb:
    image: imranvisualpath/vprdbfix
    ports:
      - "3306:3306"
    volumes:
      - auroradb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  auroraapp:
    image: imranvisualpath/vproappfix
    ports:
      - "8080:8080"
    volumes:
      - appdb:/usr/local/tomcat/webapps


  nginxweb:
    image: docker1anil/aurora_lb:v1
    ports:
      - "80:80"


volumes:
  auroradb: {}
  appdb: {}
